// PWA files emitted next to dist/WarGamer.html by build.mjs. They are used only when the app is
// served over http(s) (LAN server or any static host); file:// and the desktop app ignore them.
import { createHash } from 'node:crypto';

export const PWA_ICONS = [
  { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
  { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
  { src: 'icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
];

/** Cache name: changes whenever the app version or the built page changes. */
export function cacheName(version, html) {
  const hash = createHash('sha256').update(html).digest('hex').slice(0, 10);
  return `wargamer-v${version}-${hash}`;
}

export function manifest(version) {
  return {
    id: './',
    name: 'WarGamer — Tactical Training System',
    short_name: 'WarGamer',
    description: 'Offline tactical wargaming trainer: plan, wargame, assess.',
    version,
    start_url: './',
    scope: './',
    display: 'standalone',
    background_color: '#0f1418',
    theme_color: '#0f1418',
    categories: ['education'],
    icons: PWA_ICONS,
  };
}

/**
 * Service worker: cache-first app shell in a versioned cache.
 * - The page (/, /index.html, /WarGamer.html) is answered from the cache, so the app opens offline.
 * - /api/* (the LAN database) and other origins (optional AI calls) always go to the network.
 * - A new build changes the cache name, so the browser installs the new worker, which takes over
 *   and deletes the old caches; the page shows the new version on the next reload.
 */
export function serviceWorker(cache) {
  const assets = ['manifest.webmanifest', ...PWA_ICONS.map((i) => i.src)];
  return `// WarGamer service worker (generated by build.mjs — do not edit)
const CACHE = ${JSON.stringify(cache)};
const SHELL_KEY = 'WarGamer.html';
const SHELL_PATHS = ['', 'index.html', 'WarGamer.html'];
const ASSETS = ${JSON.stringify(assets)};
const scopePath = () => new URL(self.registration.scope).pathname;
const shellUrl = () => new URL(SHELL_KEY, self.registration.scope).href;

async function fetchShell() {
  // The page may be published as WarGamer.html or as the folder index.
  for (const p of ['WarGamer.html', './']) {
    try {
      const r = await fetch(new URL(p, self.registration.scope), { cache: 'reload' });
      if (!r.ok || !(r.headers.get('content-type') || '').includes('text/html')) continue;
      // A redirected response cannot answer a navigation; store a plain copy.
      return r.redirected ? new Response(await r.blob(), { status: 200, headers: r.headers }) : r;
    } catch (e) {}
  }
  return null;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const c = await caches.open(CACHE);
    const shell = await fetchShell();
    if (shell) await c.put(shellUrl(), shell);
    await Promise.all(ASSETS.map((a) => c.add(new Request(new URL(a, self.registration.scope), { cache: 'reload' })).catch(() => {})));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith('wargamer-') && k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  const base = scopePath();
  if (!url.pathname.startsWith(base)) return;
  const rel = url.pathname.slice(base.length);
  if (rel.startsWith('api/')) return;
  if (SHELL_PATHS.includes(rel)) {
    event.respondWith((async () => {
      const c = await caches.open(CACHE);
      const hit = await c.match(shellUrl());
      if (hit) return hit;
      const r = await fetch(req);
      if (r.ok) c.put(shellUrl(), r.clone()).catch(() => {});
      return r;
    })());
    return;
  }
  if (ASSETS.includes(rel)) {
    event.respondWith((async () => {
      const c = await caches.open(CACHE);
      const hit = await c.match(req, { ignoreSearch: true });
      if (hit) return hit;
      const r = await fetch(req);
      if (r.ok) c.put(req, r.clone()).catch(() => {});
      return r;
    })());
  }
});
`;
}
